### ISSUE TITLE
Help problems

### ISSUE THREAD

**Issue by StaticGamerYT-India** [navaneethkm004/Music-Bot-With-Filters-v2#4]
When we give the command of any help 
everything gets messed up

like when i write abc - let this be pefix
so abchelp filters
so any other command filter comes 
2nd example
abchelp lyrics 
so another command comes i.e. loop 
![Screenshot 2021-03-04 184332](https://user-images.githubusercontent.com/77852984/109969132-8b521980-7d19-11eb-8b3e-03eb7fbf3798.png)

**Comment by navaneethkm004** [comment]
Oh! I'll surely fix it!

**Comment by navaneethkm004** [comment]
Thanks for reporting it!

**Comment by StaticGamerYT-India** [comment]
Np. I fixed it do you want my code ?

**Comment by Alvin-Yu628** [comment]
When i play a music, it will just join, and then leaves, can you please help asap?

**Comment by StaticGamerYT-India** [comment]
Are you trying to run it at 24/7
It's a websocket problem

**Comment by Alvin-Yu628** [comment]
No, i use node . for starting up

**Comment by Alvin-Yu628** [comment]
do i have make it 24/7?

**Comment by Alvin-Yu628** [comment]
so whenever i ask the bot for playing a song, it just messages me, then joins, and then leaves without playing any music.

**Comment by Alvin-Yu628** [comment]
again do i have to make it 24/7? cause I am kinda confused right now...

**Comment by Alvin-Yu628** [comment]
this is the error that i am having rn:

events.js:287
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:399:19)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at PassThrough.ondata (_stream_readable.js:695:22)
    at PassThrough.emit (events.js:310:20)
    at addChunk (_stream_readable.js:286:12)
    at readableAddChunk (_stream_readable.js:268:9)
    at PassThrough.Readable.push (_stream_readable.js:209:10)
    at PassThrough.Transform.push (_stream_transform.js:152:32)
    at PassThrough.afterTransform (_stream_transform.js:96:10)
Emitted 'error' event on FFmpeg instance at:
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at FFmpeg.onerror (_stream_readable.js:729:7)
    at FFmpeg.emit (events.js:310:20)
    at Socket.processError (/Users/alvinyu/Dropbox/My Mac (Alvins-MacBook-Pro.local)/Desktop/Musicbot/node_modules/prism-media/src/core/FFmpeg.js:64:40)
    at Socket.emit (events.js:310:20)
    at errorOrDestroy (internal/streams/destroy.js:108:12)
    at onwriteError (_stream_writable.js:418:5)
    at onwrite (_stream_writable.js:445:5)
    at doWrite (_stream_writable.js:399:11)
    at writeOrBuffer (_stream_writable.js:387:5) {
  code: 'ERR_STREAM_DESTROYED'
}
